# map category name to icon
categoryIcon:
  "Database & Cache": "database"
  "Prometheus Exporter": "export"
  "Networking": "router"
  "Storage": "storage"
  "Image Registry": "cdn"
  "Big Data": "increase"
  "Message Queueing": "blockchain"
  "Web Server": "ip"
appNameReplace:
  "argo-workflows": "Argo Workflows"
  "opensearch": "OpenSearch"
  "elasticsearch": "Elasticsearch"
  "kube-prometheus": "Prometheus Operator"
  "opencart": "OpenCart"
  "aspnet-core": "ASP.NET core"
  "prestashop": "PrestaShop"
  "logstash": "Logstash"
  "jaeger": "Jaeger"
  "nats": "NATS"
  "gitea": "Gitea"
  "wordpress": "WordPress"
  "supabase": "Supabase"
  "prometheus": "Prometheus"
  "jupyterhub": "JupyterHub"
  "kibana": "Kibana"
  "mariadb": "MariaDB"
  "ejbca": "EJBCA"
  "grafana-loki": "Grafana Loki"
  "wildfly": "Wildfly"
  "spark": "Spark"
  "kubeapps": "Kubeapps"
  "zookeeper": "ZooKeeper"
  "milvus": "Milvus"
  "pytorch": "PyTorch"
  "mlflow": "MLflow"
  "flux": "Flux"
  "metallb": "MetalLB"
  "phpmyadmin": "phpMyAdmin"
  "sonarqube": "SonarQube"
  "argo-cd": "ArgoCD"
  "discourse": "Discourse"
  "solr": "Solr"
  "influxdb": "InfluxDB"
  "grafana-tempo": "Grafana Tempo"
  "oauth2-proxy": "Oauth2 Proxy"
  "contour": "Contour"
  "jasperreports": "JasperReports"
  "consul": "Consul"
  "haproxy": "HAProxy"
  "redmine": "Redmine"
  "kubernetes-event-exporter": "Kubernetes Event Exporter"
  "kiam": "kiam"
  "airflow": "Airflow"
  "phpbb": "phpBB"
  "concourse": "Concourse"
  "flink": "Flink"
  "apache": "Apache"
  "tensorflow-resnet": "TensorFlow ResNet"
  "matomo": "Matomo"
  "kuberay": "KubeRay"
  "mediawiki": "MediaWiki"
  "spring-cloud-dataflow": "Spring Cloud Data Flow"
  "grafana-mimir": "Grafana Mimir"
  "joomla": "Joomla"
  "magento": "Magento"
  "kong": "Kong"
  "sealed-secrets": "Sealed Secrets"
  "fluentd": "Fluentd"
  "cassandra": "Cassandra"
  "vault": "Vault"
  "clickhouse": "ClickHouse"
  "schema-registry": "Schema Registry"
  "moodle": "Moodle"
  "external-dns": "ExternalDNS"
  "thanos": "Thanos"
  "nginx-ingress-controller": "NGINX Ingress Controller"
  "mastodon": "Mastodon"
  "cert-manager": "CertManager"
  "kafka": "Kafka"
  "pinniped": "Pinniped"
  "parse": "Parse"
  "appsmith": "Appsmith"
  "jenkins": "Jenkins"
  "osclass": "Osclass"
  "odoo": "Odoo"
  "ghost": "Ghost"
  "keycloak": "Keycloak"
  "drupal": "Drupal"
  "grafana": "Grafana"
  "dokuwiki": "DokuWiki"
  "deepspeed": "DeepSpeed"
  "metrics-server": "Metrics Server"
  "mariadb-galera": "MariaDB Galera"
